# Generated by Django 4.0.3 on 2022-05-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0002_alter_produkty_cena'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkty',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
    ]
