# Generated by Django 4.0.3 on 2022-06-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0008_przeznaczenie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='przeznaczenie',
        ),
    ]
