# Generated by Django 4.0.3 on 2022-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0009_delete_przeznaczenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
            },
        ),
        migrations.AddField(
            model_name='produkty',
            name='tagi',
            field=models.ManyToManyField(blank=True, null=True, to='Produkty.tagi'),
        ),
    ]
